#!/usr/bin/env bash
# Description: Generate SSH routes configuration from network scan or manual input
# Usage: ./generate-routes.sh [-o output_file]
# Dependencies: none

set -euo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

OUTPUT_FILE="ssh-routes.conf"

# Parse arguments
while getopts "o:h" opt; do
    case $opt in
        o) OUTPUT_FILE="$OPTARG" ;;
        h)
            echo "Usage: $0 [-o output_file]"
            echo "Interactive tool to generate SSH routes configuration"
            exit 0
            ;;
    esac
done

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  SSH Routes Generator${NC}"
echo -e "${CYAN}========================================${NC}\n"

echo -e "${YELLOW}This tool will help you create an SSH routes configuration file.${NC}"
echo -e "${YELLOW}You'll define network segments and their corresponding jump chains.${NC}\n"

# Check if file exists
if [[ -f "$OUTPUT_FILE" ]]; then
    read -p "File $OUTPUT_FILE exists. Overwrite? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Aborted.${NC}"
        exit 0
    fi
fi

# Start building configuration
cat > "$OUTPUT_FILE" << 'EOF'
# SSH Routes Configuration
# Generated by generate-routes.sh
# Format: NETWORK/CIDR via JUMP_CHAIN

EOF

echo -e "${BLUE}First, let's configure your primary jump host (e.g., Kali on cyber polygon)${NC}\n"

read -p "Primary jump host (user@host): " PRIMARY_JUMP
read -p "Primary jump host description: " PRIMARY_DESC

cat >> "$OUTPUT_FILE" << EOF
# ==========================================
# Primary Jump Host
# ==========================================
# $PRIMARY_DESC

EOF

echo -e "\n${BLUE}Now, let's add internal networks...${NC}"
echo -e "${YELLOW}Enter networks one by one. Press Ctrl+C when done.${NC}\n"

ROUTE_NUM=1

while true; do
    echo -e "${GREEN}--- Route $ROUTE_NUM ---${NC}"
    
    read -p "Network CIDR (e.g., 192.168.1.0/24) or 'done' to finish: " NETWORK
    
    if [[ "$NETWORK" == "done" || "$NETWORK" == "DONE" ]]; then
        break
    fi
    
    # Validate CIDR format
    if [[ ! "$NETWORK" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]]; then
        echo -e "${RED}Invalid CIDR format. Try again.${NC}"
        continue
    fi
    
    read -p "Description for this network: " NET_DESC
    
    echo -e "${YELLOW}How to reach this network?${NC}"
    echo "  1) Through primary jump only ($PRIMARY_JUMP)"
    echo "  2) Through primary + internal VM (multi-hop)"
    echo "  3) Direct access (no jump)"
    read -p "Choice (1/2/3): " CHOICE
    
    case $CHOICE in
        1)
            JUMP_CHAIN="$PRIMARY_JUMP"
            ;;
        2)
            read -p "Internal VM (user@host): " INTERNAL_VM
            JUMP_CHAIN="${PRIMARY_JUMP},${INTERNAL_VM}"
            
            read -p "Add more hops? (y/n): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                read -p "Next hop (user@host): " NEXT_HOP
                JUMP_CHAIN="${JUMP_CHAIN},${NEXT_HOP}"
            fi
            ;;
        3)
            JUMP_CHAIN="direct"
            ;;
        *)
            echo -e "${RED}Invalid choice. Using primary jump.${NC}"
            JUMP_CHAIN="$PRIMARY_JUMP"
            ;;
    esac
    
    # Add to configuration
    cat >> "$OUTPUT_FILE" << EOF

# $NET_DESC
$NETWORK via $JUMP_CHAIN
EOF
    
    echo -e "${GREEN}✓ Route added${NC}\n"
    ((ROUTE_NUM++))
done

# Add default route
echo -e "\n${BLUE}Configuring default route...${NC}"
read -p "Default route for unmatched networks (user@host or 'none'): " DEFAULT_ROUTE

if [[ "$DEFAULT_ROUTE" != "none" && -n "$DEFAULT_ROUTE" ]]; then
    cat >> "$OUTPUT_FILE" << EOF

# ==========================================
# Default Route
# ==========================================
# For any network not explicitly defined above
default via $DEFAULT_ROUTE
EOF
fi

# Add footer
cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# Notes
# ==========================================
# - More specific routes are matched first
# - Default route is used if no match found
# - Use "direct" for networks accessible without jump host
# - Test routes with: ./ssh-router.sh -r ssh-routes.conf -l
EOF

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}  Configuration Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "${BLUE}Routes file created: ${NC}$OUTPUT_FILE"
echo -e "${BLUE}Total routes: ${NC}$((ROUTE_NUM - 1))"
echo -e "\n${YELLOW}Next steps:${NC}"
echo -e "  1. Review configuration: ${CYAN}cat $OUTPUT_FILE${NC}"
echo -e "  2. Test routes: ${CYAN}./ssh-router.sh -r $OUTPUT_FILE -l${NC}"
echo -e "  3. Use router: ${CYAN}./ssh-router.sh -r $OUTPUT_FILE -t <target> -c <command>${NC}"
echo ""
